//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogRoom
    {
        public int catalogRoomsID { get; set; }
        public Nullable<int> catalogHotelsID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> placesNumber { get; set; }
        public Nullable<int> roomQuantity { get; set; }
        public Nullable<float> area { get; set; }
        public Nullable<bool> free { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
