//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comfort
    {
        public int comfortID { get; set; }
        public Nullable<int> catalogHotelsID { get; set; }
        public string nameComfort { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
