//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.CatalogRooms = new HashSet<CatalogRoom>();
            this.Comforts = new HashSet<Comfort>();
        }
    
        public int catalogHotelsID { get; set; }
        public string nameH { get; set; }
        public string country { get; set; }
        public string town { get; set; }
        public string type { get; set; }
        public Nullable<int> countRooms { get; set; }
        public Nullable<int> star { get; set; }
        public Nullable<float> distance { get; set; }
        public string deck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogRoom> CatalogRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comfort> Comforts { get; set; }
    }
}
